--[[ Catalogue Mur : genere depuis le pack de constructions PACK_10_3 (1 case = 10 studs).
	Nom = libelle affiche ; Famille / Matiere servent au menu de construction ; Prix en $ (debite par le serveur).
]]
local Mur = {
	["mur_baie_arche_brique"] = { Nom = "Baie en arche", Prix = 40, Famille = "mur_baie_arche", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_arche_clin"] = { Nom = "Baie en arche", Prix = 40, Famille = "mur_baie_arche", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_arche_crepi"] = { Nom = "Baie en arche", Prix = 40, Famille = "mur_baie_arche", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_arche_enduit"] = { Nom = "Baie en arche", Prix = 40, Famille = "mur_baie_arche", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_arche_nue_brique"] = { Nom = "Baie en arche nue", Prix = 34, Famille = "mur_baie_arche_nue", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_arche_nue_clin"] = { Nom = "Baie en arche nue", Prix = 34, Famille = "mur_baie_arche_nue", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_arche_nue_crepi"] = { Nom = "Baie en arche nue", Prix = 34, Famille = "mur_baie_arche_nue", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_arche_nue_enduit"] = { Nom = "Baie en arche nue", Prix = 34, Famille = "mur_baie_arche_nue", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_arche_nue_pierre"] = { Nom = "Baie en arche nue", Prix = 34, Famille = "mur_baie_arche_nue", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_baie_arche_pierre"] = { Nom = "Baie en arche", Prix = 40, Famille = "mur_baie_arche", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_baie_barreaudee_brique"] = { Nom = "Baie barreaudée", Prix = 36, Famille = "mur_baie_barreaudee", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_barreaudee_clin"] = { Nom = "Baie barreaudée", Prix = 36, Famille = "mur_baie_barreaudee", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_barreaudee_crepi"] = { Nom = "Baie barreaudée", Prix = 36, Famille = "mur_baie_barreaudee", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_barreaudee_enduit"] = { Nom = "Baie barreaudée", Prix = 36, Famille = "mur_baie_barreaudee", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_barreaudee_pierre"] = { Nom = "Baie barreaudée", Prix = 36, Famille = "mur_baie_barreaudee", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_baie_croisee_brique"] = { Nom = "Baie croisée", Prix = 36, Famille = "mur_baie_croisee", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_croisee_clin"] = { Nom = "Baie croisée", Prix = 36, Famille = "mur_baie_croisee", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_croisee_crepi"] = { Nom = "Baie croisée", Prix = 36, Famille = "mur_baie_croisee", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_croisee_enduit"] = { Nom = "Baie croisée", Prix = 36, Famille = "mur_baie_croisee", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_croisee_pierre"] = { Nom = "Baie croisée", Prix = 36, Famille = "mur_baie_croisee", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_baie_grille_brique"] = { Nom = "Baie grillagée", Prix = 36, Famille = "mur_baie_grille", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_grille_clin"] = { Nom = "Baie grillagée", Prix = 36, Famille = "mur_baie_grille", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_grille_crepi"] = { Nom = "Baie grillagée", Prix = 36, Famille = "mur_baie_grille", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_grille_enduit"] = { Nom = "Baie grillagée", Prix = 36, Famille = "mur_baie_grille", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_grille_pierre"] = { Nom = "Baie grillagée", Prix = 36, Famille = "mur_baie_grille", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_baie_simple_brique"] = { Nom = "Baie simple", Prix = 34, Famille = "mur_baie_simple", Matiere = "Brique", Hauteur = 16.00 },
	["mur_baie_simple_clin"] = { Nom = "Baie simple", Prix = 34, Famille = "mur_baie_simple", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_baie_simple_crepi"] = { Nom = "Baie simple", Prix = 34, Famille = "mur_baie_simple", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_baie_simple_enduit"] = { Nom = "Baie simple", Prix = 34, Famille = "mur_baie_simple", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_baie_simple_pierre"] = { Nom = "Baie simple", Prix = 34, Famille = "mur_baie_simple", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_deux_baies_brique"] = { Nom = "Deux baies", Prix = 44, Famille = "mur_deux_baies", Matiere = "Brique", Hauteur = 16.00 },
	["mur_deux_baies_clin"] = { Nom = "Deux baies", Prix = 44, Famille = "mur_deux_baies", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_deux_baies_crepi"] = { Nom = "Deux baies", Prix = 44, Famille = "mur_deux_baies", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_deux_baies_enduit"] = { Nom = "Deux baies", Prix = 44, Famille = "mur_deux_baies", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_deux_baies_pierre"] = { Nom = "Deux baies", Prix = 44, Famille = "mur_deux_baies", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_arche_croix_brique"] = { Nom = "Fenêtre arche à croisillons", Prix = 38, Famille = "mur_fenetre_arche_croix", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_arche_croix_clin"] = { Nom = "Fenêtre arche à croisillons", Prix = 38, Famille = "mur_fenetre_arche_croix", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_arche_croix_crepi"] = { Nom = "Fenêtre arche à croisillons", Prix = 38, Famille = "mur_fenetre_arche_croix", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_arche_croix_enduit"] = { Nom = "Fenêtre arche à croisillons", Prix = 38, Famille = "mur_fenetre_arche_croix", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_arche_croix_pierre"] = { Nom = "Fenêtre arche à croisillons", Prix = 38, Famille = "mur_fenetre_arche_croix", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_arche_pleine_brique"] = { Nom = "Fenêtre arche pleine", Prix = 36, Famille = "mur_fenetre_arche_pleine", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_arche_pleine_clin"] = { Nom = "Fenêtre arche pleine", Prix = 36, Famille = "mur_fenetre_arche_pleine", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_arche_pleine_crepi"] = { Nom = "Fenêtre arche pleine", Prix = 36, Famille = "mur_fenetre_arche_pleine", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_arche_pleine_enduit"] = { Nom = "Fenêtre arche pleine", Prix = 36, Famille = "mur_fenetre_arche_pleine", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_arche_pleine_pierre"] = { Nom = "Fenêtre arche pleine", Prix = 36, Famille = "mur_fenetre_arche_pleine", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_arche_vitrine_brique"] = { Nom = "Fenêtre arche vitrine", Prix = 42, Famille = "mur_fenetre_arche_vitrine", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_arche_vitrine_clin"] = { Nom = "Fenêtre arche vitrine", Prix = 42, Famille = "mur_fenetre_arche_vitrine", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_arche_vitrine_crepi"] = { Nom = "Fenêtre arche vitrine", Prix = 42, Famille = "mur_fenetre_arche_vitrine", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_arche_vitrine_enduit"] = { Nom = "Fenêtre arche vitrine", Prix = 42, Famille = "mur_fenetre_arche_vitrine", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_arche_vitrine_pierre"] = { Nom = "Fenêtre arche vitrine", Prix = 42, Famille = "mur_fenetre_arche_vitrine", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_grille_brique"] = { Nom = "Fenêtre grillagée", Prix = 32, Famille = "mur_fenetre_grille", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_grille_clin"] = { Nom = "Fenêtre grillagée", Prix = 32, Famille = "mur_fenetre_grille", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_grille_crepi"] = { Nom = "Fenêtre grillagée", Prix = 32, Famille = "mur_fenetre_grille", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_grille_enduit"] = { Nom = "Fenêtre grillagée", Prix = 32, Famille = "mur_fenetre_grille", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_grille_pierre"] = { Nom = "Fenêtre grillagée", Prix = 32, Famille = "mur_fenetre_grille", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_haute_brique"] = { Nom = "Fenêtre haute", Prix = 30, Famille = "mur_fenetre_haute", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_haute_clin"] = { Nom = "Fenêtre haute", Prix = 30, Famille = "mur_fenetre_haute", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_haute_crepi"] = { Nom = "Fenêtre haute", Prix = 30, Famille = "mur_fenetre_haute", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_haute_enduit"] = { Nom = "Fenêtre haute", Prix = 30, Famille = "mur_fenetre_haute", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_haute_pierre"] = { Nom = "Fenêtre haute", Prix = 30, Famille = "mur_fenetre_haute", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_fenetre_simple_brique"] = { Nom = "Fenêtre simple", Prix = 30, Famille = "mur_fenetre_simple", Matiere = "Brique", Hauteur = 16.00 },
	["mur_fenetre_simple_clin"] = { Nom = "Fenêtre simple", Prix = 30, Famille = "mur_fenetre_simple", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_fenetre_simple_crepi"] = { Nom = "Fenêtre simple", Prix = 30, Famille = "mur_fenetre_simple", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_fenetre_simple_enduit"] = { Nom = "Fenêtre simple", Prix = 30, Famille = "mur_fenetre_simple", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_fenetre_simple_pierre"] = { Nom = "Fenêtre simple", Prix = 30, Famille = "mur_fenetre_simple", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_muret_brique"] = { Nom = "Muret", Prix = 8, Famille = "mur_muret", Matiere = "Brique", Hauteur = 4.42 },
	["mur_muret_clin"] = { Nom = "Muret", Prix = 8, Famille = "mur_muret", Matiere = "Bardage", Hauteur = 4.42 },
	["mur_muret_crepi"] = { Nom = "Muret", Prix = 8, Famille = "mur_muret", Matiere = "Crépi", Hauteur = 4.42 },
	["mur_muret_enduit"] = { Nom = "Muret", Prix = 8, Famille = "mur_muret", Matiere = "Enduit", Hauteur = 4.42 },
	["mur_muret_pierre"] = { Nom = "Muret", Prix = 8, Famille = "mur_muret", Matiere = "Pierre", Hauteur = 4.42 },
	["mur_plein_brique"] = { Nom = "Mur plein", Prix = 15, Famille = "mur_plein", Matiere = "Brique", Hauteur = 16.00 },
	["mur_plein_clin"] = { Nom = "Mur plein", Prix = 15, Famille = "mur_plein", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_plein_crepi"] = { Nom = "Mur plein", Prix = 15, Famille = "mur_plein", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_plein_enduit"] = { Nom = "Mur plein", Prix = 15, Famille = "mur_plein", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_plein_pierre"] = { Nom = "Mur plein", Prix = 15, Famille = "mur_plein", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_blanche_brique"] = { Nom = "Porte blanche", Prix = 50, Famille = "mur_porte_blanche", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_blanche_clin"] = { Nom = "Porte blanche", Prix = 50, Famille = "mur_porte_blanche", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_blanche_crepi"] = { Nom = "Porte blanche", Prix = 50, Famille = "mur_porte_blanche", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_blanche_enduit"] = { Nom = "Porte blanche", Prix = 50, Famille = "mur_porte_blanche", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_blanche_pierre"] = { Nom = "Porte blanche", Prix = 50, Famille = "mur_porte_blanche", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_bois_brique"] = { Nom = "Porte bois", Prix = 50, Famille = "mur_porte_bois", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_bois_clin"] = { Nom = "Porte bois", Prix = 50, Famille = "mur_porte_bois", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_bois_crepi"] = { Nom = "Porte bois", Prix = 50, Famille = "mur_porte_bois", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_bois_enduit"] = { Nom = "Porte bois", Prix = 50, Famille = "mur_porte_bois", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_bois_pierre"] = { Nom = "Porte bois", Prix = 50, Famille = "mur_porte_bois", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_brique"] = { Nom = "Ouverture", Prix = 20, Famille = "mur_porte", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_clin"] = { Nom = "Ouverture", Prix = 20, Famille = "mur_porte", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_crepi"] = { Nom = "Ouverture", Prix = 20, Famille = "mur_porte", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_deco_brique"] = { Nom = "Porte décorée", Prix = 60, Famille = "mur_porte_deco", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_deco_clin"] = { Nom = "Porte décorée", Prix = 60, Famille = "mur_porte_deco", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_deco_crepi"] = { Nom = "Porte décorée", Prix = 60, Famille = "mur_porte_deco", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_deco_enduit"] = { Nom = "Porte décorée", Prix = 60, Famille = "mur_porte_deco", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_deco_pierre"] = { Nom = "Porte décorée", Prix = 60, Famille = "mur_porte_deco", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_double_bois_brique"] = { Nom = "Double porte bois", Prix = 65, Famille = "mur_porte_double_bois", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_double_bois_clin"] = { Nom = "Double porte bois", Prix = 65, Famille = "mur_porte_double_bois", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_double_bois_crepi"] = { Nom = "Double porte bois", Prix = 65, Famille = "mur_porte_double_bois", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_double_bois_enduit"] = { Nom = "Double porte bois", Prix = 65, Famille = "mur_porte_double_bois", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_double_bois_pierre"] = { Nom = "Double porte bois", Prix = 65, Famille = "mur_porte_double_bois", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_double_verte_brique"] = { Nom = "Double porte verte", Prix = 65, Famille = "mur_porte_double_verte", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_double_verte_clin"] = { Nom = "Double porte verte", Prix = 65, Famille = "mur_porte_double_verte", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_double_verte_crepi"] = { Nom = "Double porte verte", Prix = 65, Famille = "mur_porte_double_verte", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_double_verte_enduit"] = { Nom = "Double porte verte", Prix = 65, Famille = "mur_porte_double_verte", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_double_verte_pierre"] = { Nom = "Double porte verte", Prix = 65, Famille = "mur_porte_double_verte", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_double_vitree_brique"] = { Nom = "Double porte vitrée", Prix = 70, Famille = "mur_porte_double_vitree", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_double_vitree_clin"] = { Nom = "Double porte vitrée", Prix = 70, Famille = "mur_porte_double_vitree", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_double_vitree_crepi"] = { Nom = "Double porte vitrée", Prix = 70, Famille = "mur_porte_double_vitree", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_double_vitree_enduit"] = { Nom = "Double porte vitrée", Prix = 70, Famille = "mur_porte_double_vitree", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_double_vitree_pierre"] = { Nom = "Double porte vitrée", Prix = 70, Famille = "mur_porte_double_vitree", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_enduit"] = { Nom = "Ouverture", Prix = 20, Famille = "mur_porte", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_garage_brique"] = { Nom = "Porte de garage", Prix = 80, Famille = "mur_porte_garage", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_garage_clin"] = { Nom = "Porte de garage", Prix = 80, Famille = "mur_porte_garage", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_garage_crepi"] = { Nom = "Porte de garage", Prix = 80, Famille = "mur_porte_garage", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_garage_enduit"] = { Nom = "Porte de garage", Prix = 80, Famille = "mur_porte_garage", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_garage_pierre"] = { Nom = "Porte de garage", Prix = 80, Famille = "mur_porte_garage", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_imposte_brique"] = { Nom = "Porte à imposte", Prix = 55, Famille = "mur_porte_imposte", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_imposte_clin"] = { Nom = "Porte à imposte", Prix = 55, Famille = "mur_porte_imposte", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_imposte_crepi"] = { Nom = "Porte à imposte", Prix = 55, Famille = "mur_porte_imposte", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_imposte_enduit"] = { Nom = "Porte à imposte", Prix = 55, Famille = "mur_porte_imposte", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_imposte_pierre"] = { Nom = "Porte à imposte", Prix = 55, Famille = "mur_porte_imposte", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_pierre"] = { Nom = "Ouverture", Prix = 20, Famille = "mur_porte", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_pleine_brique"] = { Nom = "Porte pleine", Prix = 50, Famille = "mur_porte_pleine", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_pleine_clin"] = { Nom = "Porte pleine", Prix = 50, Famille = "mur_porte_pleine", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_pleine_crepi"] = { Nom = "Porte pleine", Prix = 50, Famille = "mur_porte_pleine", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_pleine_enduit"] = { Nom = "Porte pleine", Prix = 50, Famille = "mur_porte_pleine", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_pleine_pierre"] = { Nom = "Porte pleine", Prix = 50, Famille = "mur_porte_pleine", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_service_bois_brique"] = { Nom = "Porte de service bois", Prix = 45, Famille = "mur_porte_service_bois", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_service_bois_clin"] = { Nom = "Porte de service bois", Prix = 45, Famille = "mur_porte_service_bois", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_service_bois_crepi"] = { Nom = "Porte de service bois", Prix = 45, Famille = "mur_porte_service_bois", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_service_bois_enduit"] = { Nom = "Porte de service bois", Prix = 45, Famille = "mur_porte_service_bois", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_service_bois_pierre"] = { Nom = "Porte de service bois", Prix = 45, Famille = "mur_porte_service_bois", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_service_verte_brique"] = { Nom = "Porte de service verte", Prix = 45, Famille = "mur_porte_service_verte", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_service_verte_clin"] = { Nom = "Porte de service verte", Prix = 45, Famille = "mur_porte_service_verte", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_service_verte_crepi"] = { Nom = "Porte de service verte", Prix = 45, Famille = "mur_porte_service_verte", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_service_verte_enduit"] = { Nom = "Porte de service verte", Prix = 45, Famille = "mur_porte_service_verte", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_service_verte_pierre"] = { Nom = "Porte de service verte", Prix = 45, Famille = "mur_porte_service_verte", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_service_vitree_brique"] = { Nom = "Porte de service vitrée", Prix = 50, Famille = "mur_porte_service_vitree", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_service_vitree_clin"] = { Nom = "Porte de service vitrée", Prix = 50, Famille = "mur_porte_service_vitree", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_service_vitree_crepi"] = { Nom = "Porte de service vitrée", Prix = 50, Famille = "mur_porte_service_vitree", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_service_vitree_enduit"] = { Nom = "Porte de service vitrée", Prix = 50, Famille = "mur_porte_service_vitree", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_service_vitree_pierre"] = { Nom = "Porte de service vitrée", Prix = 50, Famille = "mur_porte_service_vitree", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_simple_blanche_brique"] = { Nom = "Porte simple blanche", Prix = 40, Famille = "mur_porte_simple_blanche", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_simple_blanche_clin"] = { Nom = "Porte simple blanche", Prix = 40, Famille = "mur_porte_simple_blanche", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_simple_blanche_crepi"] = { Nom = "Porte simple blanche", Prix = 40, Famille = "mur_porte_simple_blanche", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_simple_blanche_enduit"] = { Nom = "Porte simple blanche", Prix = 40, Famille = "mur_porte_simple_blanche", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_simple_blanche_pierre"] = { Nom = "Porte simple blanche", Prix = 40, Famille = "mur_porte_simple_blanche", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_simple_bois_brique"] = { Nom = "Porte simple bois", Prix = 40, Famille = "mur_porte_simple_bois", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_simple_bois_clin"] = { Nom = "Porte simple bois", Prix = 40, Famille = "mur_porte_simple_bois", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_simple_bois_crepi"] = { Nom = "Porte simple bois", Prix = 40, Famille = "mur_porte_simple_bois", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_simple_bois_enduit"] = { Nom = "Porte simple bois", Prix = 40, Famille = "mur_porte_simple_bois", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_simple_bois_pierre"] = { Nom = "Porte simple bois", Prix = 40, Famille = "mur_porte_simple_bois", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_simple_deco_brique"] = { Nom = "Porte simple décorée", Prix = 48, Famille = "mur_porte_simple_deco", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_simple_deco_clin"] = { Nom = "Porte simple décorée", Prix = 48, Famille = "mur_porte_simple_deco", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_simple_deco_crepi"] = { Nom = "Porte simple décorée", Prix = 48, Famille = "mur_porte_simple_deco", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_simple_deco_enduit"] = { Nom = "Porte simple décorée", Prix = 48, Famille = "mur_porte_simple_deco", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_simple_deco_pierre"] = { Nom = "Porte simple décorée", Prix = 48, Famille = "mur_porte_simple_deco", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_simple_pleine_brique"] = { Nom = "Porte simple pleine", Prix = 40, Famille = "mur_porte_simple_pleine", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_simple_pleine_clin"] = { Nom = "Porte simple pleine", Prix = 40, Famille = "mur_porte_simple_pleine", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_simple_pleine_crepi"] = { Nom = "Porte simple pleine", Prix = 40, Famille = "mur_porte_simple_pleine", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_simple_pleine_enduit"] = { Nom = "Porte simple pleine", Prix = 40, Famille = "mur_porte_simple_pleine", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_simple_pleine_pierre"] = { Nom = "Porte simple pleine", Prix = 40, Famille = "mur_porte_simple_pleine", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_simple_verre_sombre_brique"] = { Nom = "Porte simple verre sombre", Prix = 48, Famille = "mur_porte_simple_verre_sombre", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_simple_verre_sombre_clin"] = { Nom = "Porte simple verre sombre", Prix = 48, Famille = "mur_porte_simple_verre_sombre", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_simple_verre_sombre_crepi"] = { Nom = "Porte simple verre sombre", Prix = 48, Famille = "mur_porte_simple_verre_sombre", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_simple_verre_sombre_enduit"] = { Nom = "Porte simple verre sombre", Prix = 48, Famille = "mur_porte_simple_verre_sombre", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_simple_verre_sombre_pierre"] = { Nom = "Porte simple verre sombre", Prix = 48, Famille = "mur_porte_simple_verre_sombre", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_porte_verre_sombre_brique"] = { Nom = "Porte verre sombre", Prix = 58, Famille = "mur_porte_verre_sombre", Matiere = "Brique", Hauteur = 16.00 },
	["mur_porte_verre_sombre_clin"] = { Nom = "Porte verre sombre", Prix = 58, Famille = "mur_porte_verre_sombre", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_porte_verre_sombre_crepi"] = { Nom = "Porte verre sombre", Prix = 58, Famille = "mur_porte_verre_sombre", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_porte_verre_sombre_enduit"] = { Nom = "Porte verre sombre", Prix = 58, Famille = "mur_porte_verre_sombre", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_porte_verre_sombre_pierre"] = { Nom = "Porte verre sombre", Prix = 58, Famille = "mur_porte_verre_sombre", Matiere = "Pierre", Hauteur = 16.00 },
	["mur_vitrine_brique"] = { Nom = "Vitrine", Prix = 45, Famille = "mur_vitrine", Matiere = "Brique", Hauteur = 16.00 },
	["mur_vitrine_clin"] = { Nom = "Vitrine", Prix = 45, Famille = "mur_vitrine", Matiere = "Bardage", Hauteur = 16.00 },
	["mur_vitrine_crepi"] = { Nom = "Vitrine", Prix = 45, Famille = "mur_vitrine", Matiere = "Crépi", Hauteur = 16.00 },
	["mur_vitrine_enduit"] = { Nom = "Vitrine", Prix = 45, Famille = "mur_vitrine", Matiere = "Enduit", Hauteur = 16.00 },
	["mur_vitrine_pierre"] = { Nom = "Vitrine", Prix = 45, Famille = "mur_vitrine", Matiere = "Pierre", Hauteur = 16.00 },
}
return Mur
